#Minecraft server properties
# ''(Fecha de modificación del archivo)''
# EJEMPLO CON LAS ESPECIFICACIONES DE CADA PARAMETRO

# Tiempo de espera para que el servidor se pause cuando no hay jugadores (en segundos). -1 es el valor por defecto, 0 desactiva la pausa. (Para evitar cuelgues del servidor, se recomienda dejarlo en -1)
pause-when-empty-seconds=-1.

# Area de protección del spawn (en bloques). 16 es el valor por defecto, 0 desactiva la protección.
spawn-protection=16

# Tiempo máximo de ejecución de un tick (en milisegundos). 60000 es el valor por defecto, -1 desactiva el límite. (Para evitar cuelgues del servidor, se recomienda dejarlo en 60000)
max-tick-time=60000

# Opciones de generador de mundo (dejar vacío para que el servidor use la semilla por defecto)
generator-settings=

# Forzar el modo de juego al entrar al servidor (true=activado, false=desactivado). Si está activado, los jugadores entrarán al servidor con el modo de juego definido en la opción "gamemode".
force-gamemode=false

# Activar el Nether
allow-nether=true

# Modo de juego default (survival=0, creativo=1, aventura=2, espectador=3)
gamemode=0

# Poder consultar el servidor desde páginas externas (true=activado, false=desactivado)
enable-query=false

# Tiempo hasta que un jugador es considerado inactivo (en minutos). 0 = desactivado
player-idle-timeout=0

# Dificultad del juego (pacífico=0, fácil=1, normal=2, difícil=3)
difficulty=1

# Spawn de monstruos (true=activado, false=desactivado)
spawn-monsters=true

# Nivel de permisos de los operadores (1=permite comandos básicos, 2=permite comandos de moderador, 3=permite comandos de administrador, 4=permite todos los comandos)
op-permission-level=4

# Codigo hash del paquete de recursos (dejar vacío para que el servidor no verifique el paquete de recursos)
resource-pack-hash=

# Habilitar logros de los jugadores (true=activado, false=desactivado)
announce-player-achievements=true

# Combate entre jugadores
pvp=true

# Enviar estadísticas del servidor a Mojang (true=activado, false=desactivado) (A partir de la 1.18 ya no se usa)
snooper-enabled=true

# Tipo de mundo (DEFAULT=normal, FLAT=plano, LARGE_BIOMES=biomas grandes, AMPLIFIED=amplificado, CUSTOMIZED=personalizado)
level-type=DEFAULT

# Modo de juego hardcore (true=activado, false=desactivado)
hardcore=false

# Activar el uso de bloques de comandos (true=activado, false=desactivado)
enable-command-block=false

# Jugadores máximos permitidos en el servidor
max-players=20

# Nivel de compresión de red (en bytes). 256 es el valor por defecto
network-compression-threshold=256

# Tamaño máximo del mundo (en bloques). 29999984 es el tamaño máximo permitido por Minecraft.
max-world-size=29999984

# Puerto del servidor (el puerto por defecto es 25565)
server-port=25565

# Ip del servidor (dejar vacío para que el servidor use la ip de la máquina)
server-ip=

# Spawn de NPCs (true=activado, false=desactivado)
spawn-npcs=true

# Permitir vuelo (elytras por ejemplo) (true=activado, false=desactivado)
allow-flight=false

# Nombre del mundo
level-name=world

# Distancia de visualización (en chunks). 10 es el valor por defecto, 32 es el máximo permitido.
view-distance=10

# Enlace del paquete de recursos (dejar vacío para que el servidor no use ningún paquete de recursos)
resource-pack=

# Activar el spawn de animales (true=activado, false=desactivado)
spawn-animals=true

# Lista de jugadores permitidos (true=activado, false=desactivado). Si está activado, solo los jugadores en la lista blanca podrán entrar al servidor.
white-list=false

# Generación de estructuras (true=activado, false=desactivado)
generate-structures=true

# Modo premium (true=activado, false=desactivado). Si está activado, solo los jugadores con una cuenta premium de Minecraft podrán entrar al servidor.
online-mode=true

# Altura máxima de construcción (en bloques). 256 es el valor por defecto, 512 es el máximo permitido.
max-build-height=256

# Semilla del mundo (dejar vacío para que el servidor genere una semilla aleatoria)
level-seed=

# Presentacion del servidor (mensaje que aparece en la lista de servidores)
motd=Un servidor de Minecraft en español

# Habilitar RCON (Opcion para administración remota) (true=activado, false=desactivado)
enable-rcon=false